inicio/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView , LogoutView

app_name = "inicio"
urlpatterns = [
    
    path('', views.index, name="index"),
    path('filtro_secciones/<int:seccion_id>', views.filtro_secciones, name="filtro_secciones"),
    path('<int:articulo_id>', views.articulo, name="articulo"),
    path('articulo_alta', views.articulo_alta, name="articulo_alta"),
    path('articulo_editar/<int:articulo_id>', views.articulo_editar, name="articulo_editar"),
    path('articulo_eliminar/<int:articulo_id>', views.articulo_eliminar, name="articulo_eliminar"),
    path('leer_mas_tarde/<int:articulo_id>', views.leer_mas_tarde, name="leer_mas_tarde"),
    path('login/',LoginView.as_view( template_name = 'registrtion/login.html') , name="login"),
    path('logout/',LogoutView.as_view( template_name = 'registration/logged_out.html') , name="logout"),
    path('registro/', views.registro, name="registro"),
     path("agregar_producto/<int:producto_id>/", views.agregar_producto, name="agregar_producto"),
     path('carrito/', views.carrito, name="carrito"),
     path("eliminar_producto/<int:producto_id>/", views.eliminar_producto, name="eliminar_producto"),
      path("restar_producto/<int:producto_id>/", views.restar_producto, name="restar_producto"),
    path("limpiar_carro/", views.limpiar_carro, name="limpiar_carro"),
    path('acerca_de/', views.acerca_de, name="acerca_de"),
    path('contacto/', views.contacto, name="contacto"),
   
    
    
    
]

web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("inicio.urls")),
   

    
    
    
     
    
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inicio/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Seccion(models.Model):
    descripcion = models.CharField(max_length=64, null=False)

    def __str__(self):
        return f"{self.descripcion}"

class Articulo(models.Model):
    seccion = models.ForeignKey(Seccion, on_delete=models.CASCADE, related_name="clasificacion_seccion")
    fecha_publicacion = models.DateField(null= False)
    titulo = models.CharField(max_length=250, null=False)
    precio = models.FloatField()
    contenido = models.CharField(max_length=2000, null=False)
    imagen = models.FileField(upload_to='imagenes/')
    
    publicador = models.ForeignKey(User, on_delete=models.CASCADE, related_name="publicador")

    def __str__(self):
        return f"{self.fecha_publicacion} - {self.titulo} ({self.publicador})"

class LeerMasTarde(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name="usuario")
    publicaciones = models.ManyToManyField(Articulo)

    def __str__(self):
        return f"{self.usuario} - {self.publicaciones}"

inicio/forms.py
from django import forms
from django.forms.fields import CharField
from .models import Articulo
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class FormArticulo(forms.ModelForm):

    #campos del modelo
    class Meta:
        model = Articulo
        fields = ('seccion', 'fecha_publicacion', 'titulo', 'contenido', 'imagen','precio')
        widgets = {
            'fecha_publicacion': forms.SelectDateWidget(attrs={'class': 'pub_fecha_publicacion'}),
            'titulo': forms.TextInput(attrs={'class': 'pub_titulo'}),
            'contenido': forms.Textarea(attrs={'class': 'pub_contenido'}),
            'imagen': forms.FileInput(attrs={'name':'imagen_adjunta', 'class': 'pub_imagen'}),
            'precio':forms.TextInput(attrs={'class':'pub_precio'}),
        }

class UserRegisterform(UserCreationForm):
    email= forms.EmailField()
    password1 =CharField(label='Contraseña', widget=forms.PasswordInput)
    password2 =CharField(label='Confirma contraseña', widget=forms.PasswordInput)
    
    class Meta:
         model = User
         fields = ['username','email', 'password1', 'password2']
         help_texts = {k:"" for k in fields}

inicio/views.py
from django.contrib.auth.models import User

from django.http.response import HttpResponseRedirect
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse
from .forms import *
from .forms import UserRegisterform
from .models import Articulo, Seccion
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# from django.contrib.auth.decorators import permission_required

# Create your views here.

from django.shortcuts import render, redirect
from .carro import Carro
from inicio.models import Articulo  



def agregar_producto(request, producto_id):
    carro= Carro(request)
    producto=Articulo.objects.get(id=producto_id)
    carro.agregar(producto= producto)
    return redirect("inicio:carrito") 

def eliminar_producto(request, producto_id):
    carro= Carro(request)
    producto=Articulo.objects.get(id=producto_id)
    carro.eliminar(producto = producto)
    return redirect("inicio:carrito") 

def restar_producto(request, producto_id):
    carro= Carro(request)
    producto=Articulo.objects.get(id=producto_id)
    carro.restar_producto(producto = producto)
    return redirect("inicio:carrito") 

def limpiar_carro(request):
    carro= Carro(request)
    carro.limpiar_carro()
    return redirect("inicio:carrito") 

def index(request):
    if "leer_mas_tarde" not in request.session:
        request.session["leer_mas_tarde"] = []
    return render(request,"blog/index.html", {
        "lista_articulos": Articulo.objects.all().order_by('fecha_publicacion')[:10],
        "lista_articulos2": Articulo.objects.all(),
        "lista_secciones": Seccion.objects.all(),
        "leer_mas_tarde": request.session["leer_mas_tarde"],
    })
   
def carrito(request):         
    return render(request, "blog/carrito.html")

def acerca_de(request):         
    return render(request, "blog/acerca_de.html")

def contacto(request):         
    return render(request, "blog/contacto.html")
    


def articulo(request, articulo_id):
    un_articulo = get_object_or_404(Articulo, id=articulo_id)
    return render(request, "blog/articulo.html", {
        "articulo": un_articulo
    })

def articulo_alta(request):
    if request.method == "POST":
        user = User.objects.get(username=request.user)
        form = FormArticulo(request.POST, request.FILES, instance=Articulo(imagen=request.FILES['imagen'], publicador=user))      
        if form.is_valid():
            form.save()
           
            return redirect("inicio:index")          
    else:
        form = FormArticulo(initial={'fecha_publicacion':timezone.now()})
        return render(request, "blog/articulo_nuevo.html", {
            "form": form
        })

def articulo_editar(request, articulo_id):
    un_articulo = get_object_or_404(Articulo, id=articulo_id)
    if request.method == "POST":  
        user = User.objects.get(username=request.user)   
        un_articulo.publicador = user
        form = FormArticulo(data=request.POST, files=request.FILES, instance=un_articulo)
        if form.is_valid():
            form.save()
            return redirect("inicio:index")
    else:
        form = FormArticulo(instance = un_articulo)
        return render(request, 'blog/articulo_edicion.html', {
            "articulo": un_articulo,
            "form": form
        })

def articulo_eliminar(request, articulo_id):
    un_articulo = get_object_or_404(Articulo, id=articulo_id)
    un_articulo.delete()
    return redirect("inicio:index")

def filtro_secciones(request, seccion_id):
    una_seccion = get_object_or_404(Seccion, id=seccion_id)
    queryset = Articulo.objects.all()
    queryset = queryset.filter(seccion=una_seccion)
    return render(request,"blog/index.html", {
        "lista_articulos": queryset,
        "lista_secciones": Seccion.objects.all(),
        "seccion_seleccionada": una_seccion
    })

@login_required
def leer_mas_tarde(request, articulo_id):
    un_articulo = get_object_or_404(Articulo, id=articulo_id)
    for id in request.session["leer_mas_tarde"]:
        if id == articulo_id:
            #existe el articulo
            return HttpResponseRedirect(reverse("sitio:articulo", args=(un_articulo.id,)))            
    request.session["leer_mas_tarde"] += [articulo_id]
    return HttpResponseRedirect(reverse("inicio:articulo", args=(un_articulo.id,)))   

    
def registro(request):
    if request.method == 'POST':
        form =  UserRegisterform(request.POST)
        if form.is_valid():
            form.save()
            username=form.cleaned_data['username']
            messages.success(request, f'Usuario: {username} creado')
           
            return redirect("inicio:index")
    else: 
        form = UserRegisterform()
    context = {'form' : form}
    return render(request,"registration/registro.html", context )

inicio/templates/blog/acerca_de.html
{% extends "blog/layout.html" %}
{% block content %}

<h1 class="text-center">jaguarete Kaa S.A. </h1>
<p class="text-center" >Somos una empresa comprometida a ofrecer a sus clientes los productos de la mayor calidad a los mejores precios mediante un servicio personalizado a cada uno de nuestros clientes.
</p>
<p class="text-center">Somos una empresa líder en el mundo de la moda, que proporciona los elementos necesarios para resaltar su belleza.Proporcionar a los miembros de la empresa el clima laboral adecuado para desarrollarse personal y profesionalmente.
</p>

{% endblock%}

inicio/templates/blog/articulo.html
{% extends "blog/layout.html" %}
{% block content %}
<div class="wrapper fadeInDown">
    <div id="formContent">
          <h2>{{ articulo.titulo }}</h2>
      <div class="alert alert-info" role="alert">{{ articulo.seccion }}</div>
              <p><span class="publicacion_fecha" >{{ articulo.fecha_publicacion }}</span></p>

      {% for un_articulo in lista_articulos %}  
                         <div>             
                          {% if user.is_authenticated %}
                          {% if user.is_staff %} 
                                         {%else %}
                                    <a role="button" class="btn btn-outline-warning" href="{% url 'inicio:agregar_producto' un_articulo.id %} ">agregar</a>
                                           {%endif%}
                          {%endif%} 
                              
                              {% if perms.sitio.change_articulo %}
                                           <a class="btn btn-primary" href="{% url 'inicio:articulo_editar' un_articulo.id %}">Modificar</a>
                              {% endif %}
                                           {% if perms.sitio.delete_articulo %} 
                                           <a class="btn btn-primary" href="{% url 'inicio:articulo_eliminar' un_articulo.id %}">Eliminar</a>  
                                           {% endif %}
                                 
                                      
                           </div>
       
                          
                          
                                                                            
       {% endfor %}
<a href="{% url 'inicio:leer_mas_tarde' articulo.id %}">Leer Mas Tarde</a>
<p><img src="{{ media_url  }}{{ articulo.imagen.url }}" alt="{{ articulo.imagen.name }}" /></p>
<h3>Contenido:</h3>
<p id="contenido">{{ articulo.contenido |safe }}</p>
<p>Precio: <span >{{ articulo.precio }}</span></p>
  <p>Publicado por <span >{{ articulo.publicador }}</span></p>
  
<!-- {% if user.is_authenticated %}
    
  
  {% if user.is_staff %} 
          {%else %}
             <a role="button" class="btn btn-outline-warning" href="{% url 'carro:agregar' producto.id % } ">agregar</a>
          {%endif%}
{%endif%} -->

  <br>           
<a href="{% url 'inicio:index'%}">Volver</a>

</div>
</div>
{% endblock %}

inicio/templates/blog/articulo_edicion.html
{% extends "blog/layout.html" %}
{% block content %}
<h3>Publicar un Articulo</h3>
<form enctype="multipart/form-data" action="{% url 'inicio:articulo_editar' articulo.id %}" method="post" >
    {% csrf_token %}
    <div class="form-group row">
        <label for="seccion_input"  class="col-sm-2 col-form-label">Seccion:</label> {{ form.seccion }} {{ form.seccion.errors }}
    </div>
    <div class="form-group row">
        <label for="titulo_input"  class="col-sm-2 col-form-label">Titulo:</label> {{ form.titulo }} {{ form.titulo.errors }}
    </div>
    <div class="form-group row">
        <label for="publicacion_input"  class="col-sm-2 col-form-label">Fecha de Publicacion:</label> {{ form.fecha_publicacion }} {{ form.fecha_publicacion.errors }}
    </div>
    <div class="form-group row">
        <label for="imagen_input"  class="col-sm-2 col-form-label">Imagen Adjunta:</label> {{ form.imagen }} {{ form.imagen.errors }}
    </div>
    <div class="form-group row"  class="col-sm-2 col-form-label">
        <label for="contenido_input">Contenido:</label> {{ form.contenido }} {{ form.contenido.errors }}
        <script>$("#id_contenido").removeAttr("required");</script>
    </div>
    <div class="form-group row">
        <label for="titulo_input"  class="col-sm-2 col-form-label">Precio:</label> {{ form.precio }} {{ form.precio.errors }}
    </div>
    <div class="col-auto">
               <input type="submit" class="btn btn-primary" value="Editar">
    </div>
</form>
<a href="{% url 'inicio:index'%}">Volver</a>
{% endblock %}

inicio/templates/blog/articulo_nuevo.html
{% extends "blog/layout.html" %}
{% block content %}

<h3>Publicar un Articulo</h3>
<form enctype="multipart/form-data" action="{% url 'inicio:articulo_alta' %}" method="post" >
    {% csrf_token %}
    <div class="form-group row">
        <label for="seccion_input"  class="col-sm-2 col-form-label">Seccion:</label> {{ form.seccion }} {{ form.seccion.errors }}
    </div>
    <div class="form-group row">
        <label for="titulo_input"  class="col-sm-2 col-form-label">Titulo:</label> {{ form.titulo }} {{ form.titulo.errors }}
    </div>
    <div class="form-group row">
        <label for="publicacion_input"  class="col-sm-2 col-form-label">Fecha de Publicacion:</label> {{ form.fecha_publicacion }} {{ form.fecha_publicacion.errors }}
    </div>
    <div class="form-group row">
        <label for="imagen_input"  class="col-sm-2 col-form-label">Imagen Adjunta:</label> {{ form.imagen }} {{ form.imagen.errors }}
    </div>
    <div class="form-group row"  class="col-sm-2 col-form-label">
        <label for="contenido_input">Contenido:</label><br> {{ form.contenido }} {{ form.contenido.errors }}
        <script>$("#id_contenido").removeAttr("required");</script>
    </div>
    <div class="form-group row">
        <label for="titulo_input"  class="col-sm-2 col-form-label">Precio:</label> {{ form.precio }} {{ form.precio.errors }}
    </div>
    <div class="col-auto">
        <a class="btn btn-secondary" type="button" href="{% url 'inicio:index'%}">Volver</a>
        <input type="submit" class="btn btn-primary" value="Publicar">
    </div>
</form>



{% endblock %}

inicio/templates/blog/carrito.html
{% extends "blog/layout.html" %}
{% block content %}





{{importe_total}}


<table class="table">
    <thead>
      <tr>
        <th>Articulo</th>
        <th>contenido</th>
        <th>cantidad</th>
        <th>precio</th>
        <th>agregar/quitar</th>
        <th>eliminar Articulo</th>
        <th>Vaciar Carrito</th>



      </tr>
    </thead>
    <tbody>
        {% if request.session.carro.items %}
        {% for key, value in request.session.carro.items %}
            <tr>
                <td>{{value.titulo}}</td>
                <td>{{value.contenido}}</td>
               
                <td>{{value.cantidad}}</td>
                <td>{{value.precio}}</td>
                <td>
                <a href="{%url 'inicio:agregar_producto' value.producto_id%}" class="btn btn-sm btn-success">+</a>
                <a href="{%url 'inicio:restar_producto' value.producto_id%}" class="btn btn-sm btn-success">-</a>
                 </td>
                 
                 <td>
                     <a href="{%url 'inicio:eliminar_producto' value.producto_id%}" class="btn btn-sm btn-success">-</a>
                     </td>
                     <td>
                        <a href="{%url 'inicio:limpiar_carro'%}" class="btn btn-sm btn-success">-</a>
                        </td>
            </tr>
        {% endfor%}
    {% else %}
        <tr>
            <td colspan="3">
                <div class="alert alert danger text-center">
                    sin productos

                </div>


            </td>

        </tr>
    {%endif%}

      
    </tbody>
  </table>


  <p>total: {{importe_total}} </p>


  <a href="{%url 'inicio:index'%}" class="btn btn-sm btn-success">Seguir comprando
  </a>

 

{% endblock %}

inicio/templates/blog/contacto.html
{% extends "blog/layout.html" %}
{% block content %}
<div class="wrapper fadeInDown">
    <div id="formContent">
  
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div >
                <form  method="post">
                    <fieldset>
                        <legend class="text-center header">Contactenos</legend>

                        <div class="form-group">
                            <span ><i class="fa fa-user bigicon"></i></span>
                            <div class="col-md-8">
                                <input id="fname" name="name" type="text" placeholder="Nombre" class="form-control">
                            </div>
                        </div>
                        

                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"><i class="fa fa-envelope-o bigicon"></i></span>
                            <div class="col-md-8">
                                <input id="email" name="email" type="text" placeholder="Email " class="form-control">
                            </div>
                        </div>

                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"><i class="fa fa-phone-square bigicon"></i></span>
                            <div class="col-md-8">
                                <input id="phone" name="phone" type="text" placeholder="Telefono" class="form-control">
                            </div>
                        </div>

                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"><i class="fa fa-pencil-square-o bigicon"></i></span>
                            <div class="col-md-8">
                                <textarea class="form-control" id="message" name="munsaje" placeholder="Ingrese aqui su mensaje"></textarea>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-12 text-center">
                                <button type="submit" class="btn btn-primary btn-lg">enviar</button>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>

    </div>
</div>

{% endblock%}

inicio/templates/blog/index.html
{% extends "blog/layout.html" %}
{% block content %}

<h2 style="text-align:center;">Articulos</h2>
    {% if seccion_seleccionada %}
        <div role="alert"style="text-align:center;">{{ seccion_seleccionada }}</div>
    {% else %}
        <div role="alert"style="text-align:center;" >Todos los Articulos</div>
    {% endif %}
 <div class="container">
   <div class="row">
        {% for un_articulo in lista_articulos %}  
   <div class="col-md-4 ">
                   
            
            <div class="card" style="width: 100%; margin: 5px 5px;" >
                <img src="{{un_articulo.imagen.url}}" class="card-img-top" alt="...">
                                <div class="card-body">
                   
                                     <h5 class="card-title">{{un_articulo.titulo}}</h5>
                                     
                                          <a  class="btn btn-primary" href="{% url 'inicio:articulo' un_articulo.id %}">Ver {{un_articulo.id}}</a>             
        
                
             
                                         {% if perms.sitio.change_articulo %}
                                        <a class="btn btn-primary" href="{% url 'inicio:articulo_editar' un_articulo.id %}">Modificar</a>
                                        {% endif %}
                                        {% if perms.sitio.delete_articulo %} 
                                        <a class="btn btn-primary" href="{% url 'inicio:articulo_eliminar' un_articulo.id %}">Eliminar</a>  
                                        {% endif %}
                                        --- {{un_articulo}}

                                        <h5 class="card-title">{{un_articulo.precio}}</h5>

                                        {% if user.is_authenticated %}
                                                {% if user.is_staff %} 
                                                               {%else %}
                                                          <a role="button" class="btn btn-outline-warning" href="{% url 'inicio:agregar_producto' un_articulo.id %} ">agregar</a>
                                                                 {%endif%}
                                                {%endif%} 
                                    </div>
             </div>              
            </div>                                         
        {% empty %}
            <li>No hay articulos en ésta Sección.</li>
        {% endfor %}
    </div>
</div>
   
    
    
    {% if perms.sitio.add_articulo %}
   
    <h3>Leer mas tarde</h3>
    <ul>
        {% for articulo in leer_mas_tarde %}
            <li>{{articulo}}</li>
        {% empty %}
            <li>No hay articulos para leer mas tarde.</li>
        {% endfor %}
    </ul>
    {% endif %}
{% endblock %}

inicio/templates/blog/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Desarrollo Web con Python y JavaScript</title>
        
        
        <!-- Styles -->
    <link href="{% static 'css/gestion.css'%}" rel="stylesheet">
    <!-- Bootstrap-->
   
           
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
           <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
        <script src="{% static 'scripts.js' %}"></script>

    </head>

    
   


    <body>
      
      <header>
     
        <div class="wrappersanti">
         <img src="{% static 'img/2.png'%} " class="logo" alt="Responsive image"></img>
          
          <nav>
            <ul id="nav-mobile" class="right hide-on-med-and-down" >
              

              {% if user.is_authenticated %}
              Estas conectado como: {{ user.get_username }} <a  href="{% url 'logout'%}">Salir</a>
              
  
                      {% if user.is_staff %} 
                      {%else %}
                      <a href="{% url 'inicio:carrito'%}">Carrito</a>
                      {%endif%}

              {%else %}
              <a  href="{% url 'login'%}?next={{request.path}}">Login</a>
              <a href="{% url 'inicio:registro'%}">Registro</a>
            {%endif%}

             
              
          </nav>
        </div>
      </header>
      

            

          <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
              
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              
              
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'inicio:index' %}">Home</a>
                  </li>
                  

                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Categorias
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      {% for seccion in lista_secciones %}
                                  <a class="dropdown-item" href="{% url 'inicio:filtro_secciones' seccion.id%}">{{ seccion }}</a>
                              {% endfor %}
                    </div>
                 </li>
                 
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'inicio:acerca_de' %}">Acerca De</a>
                  </li>


                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'inicio:contacto' %}">Contacto</a>
                  </li>
                            {% if perms.sitio.add_articulo %}
                                <li class="nav-item">
                               <a class="nav-link active" href="{% url 'inicio:articulo_alta'%}">Nuevo Producto</a>
                              
                               </li>
                               {% endif %}

                        
                </ul>
                

               


                            <form class="d-flex">
                  <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
              </div>
            </div>
          </nav>
            {% if messages %}
              {% for message in messages%}
                <div class="alert alert-primary" role="alert"
                   {{message.tags}} >
                    {{message}}
                </div>
              {%endfor%}
            {%endif%}

         
          <br>
      
            {% block content %}


            {% endblock %}
      


             <!-- Footer -->
    <footer class="footer text-faded text-center py-5">
      <div class="container">
        <p class="m-0">
	        <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
	        <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
	        <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
	    </p>
        <p class="m-0 mbt">
        	<a href="sample.html" class="link">Política de privacidad</a> ·
        	<a href="sample.html" class="link">Aviso legal</a> ·
        	<a href="sample.html" class="link">Cookies</a>
		</p>
        <p class="m-0 mbt1">&copy; Garrido Santiago R.</p>
      </div>
	</footer>

         <!-- Bootstrap -->

         <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src=" {% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    </body>
</html>